name: AML Lab5 Pipeline

on:
  push:
    branches:
      - lab5_mlops_tumor_detection
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_SUBSCRIPTION_ID: a485bb50-61aa-4b2f-bc7f-b6b53539b9d3
  AZURE_RESOURCE_GROUP: rg-60107070
  AZURE_ML_WORKSPACE: GoodReadsReview-Analysis-60107070

jobs:
  aml_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Azure CLI
        uses: azure/cli@v2

      - name: Install Azure ML CLI extension
        run: |
          az extension add -n ml --yes
          az extension update -n ml

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Install Azure ML Python SDK
        run: |
          python -m pip install --upgrade pip
          pip install azure-ai-ml azure-identity joblib numpy

      - name: Run training pipeline
        env:
          AZUREML_SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}
          AZUREML_RESOURCE_GROUP: ${{ env.AZURE_RESOURCE_GROUP }}
          AZUREML_WORKSPACE_NAME: ${{ env.AZURE_ML_WORKSPACE }}
        run: |
          python pipeline_job.py

      - name: Deploy latest model to endpoint
        env:
          AZUREML_SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}
          AZUREML_RESOURCE_GROUP: ${{ env.AZURE_RESOURCE_GROUP }}
          AZUREML_WORKSPACE_NAME: ${{ env.AZURE_ML_WORKSPACE }}
        run: |
          python src/deploy_endpoint.py
